### PR TITLE
Corrected Language CN and TW

### PR DESCRIPTION
**Pull request by MystPhysX**
Changed 莱特币 (Litecoin) to 帽子币 (FedoraCoin) in both the Taiwanese
Mandarin and Chinese Mandarin language packs. Shout-out to ndb9k for
pointing out the error and providing the fix.

### CODE REVIEW

**Comment by MystPhysX** [comment]
Yo tips, where are you?

**Comment by MystPhysX** [comment]
Sweet. Are things finally moving again?

**Comment by icanprogram** [comment]
Yessir.

We're pushing out the new branding tomorrow.
Are you available to do an OS X build somewhere between now and a week or so?

**Comment by MystPhysX** [comment]
Push the update, notify me. If I'm awake I'll have it ready within an hour.

You won't believe how badly I've been wanting things to start up again.

**Comment by icanprogram** [comment]
@MystPhysX just pushed it!

**Comment by MystPhysX** [comment]
Has the logo changed?

**Pull request merged**
